trigger:
  batch: true
  branches:
    include:
    - "*"

variables:
    apiBuildVmImage: 'windows-2019'

stages:
- stage: BuildAndTestApi
  displayName: 'Build and Test API'
  dependsOn: []

  jobs:
  - job: BuildAndRunAPIUnitTests
    displayName: "API: Build and Execute Unit Tests"

    pool: $(apiBuildVmImage)

    steps:
    - checkout: self
      submodules: true

    - task: CmdLine@2
      displayName: 'Dump Environment Variables'
      inputs:
        script: 'printenv'

    