version: "3.8"

services:
  api:
    build: "api"
    depends_on:
      - "sqlserver"
    environment:
      ConnectionStrings:ReferenceAppConnectionString: "Data Source=sqlserver;Initial Catalog=reference_app_dev;User Id=sa;Password=yourStrong(!)Password"
    ports:
      - "80:80"
  sqlserver:
    environment:
      ACCEPT_EULA: "y"
      SA_PASSWORD: "yourStrong(!)Password"
    image: "microsoft/mssql-server-windows-developer"
    ports:
      - "1433:1433"
volumes:
  sql-server-data:
